# fly.toml app configuration file generated for mod7-rough-forest-1289 on 2025-03-11T17:11:28-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mod7-rough-forest-1289'
primary_region = 'den'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
[build]
  image = "flyio/hellofly:latest"
  dockerfile = "Dockerfile.test"
